import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { pickBestCandidate } from "./youtube.js";
import type { SourceTrack } from "../types/index.js";

function track(overrides: Partial<SourceTrack> = {}): SourceTrack {
  return {
    id: "1",
    title: "Blood",
    artists: ["Knocked Loose"],
    album: "A Different Shade of Blue",
    durationMs: 150_000,
    ...overrides,
  };
}

function candidate(title: string, artist: string, durationSec: number) {
  return {
    title,
    artist,
    durationSec,
    sourceUrl: `https://www.youtube.com/watch?v=test`,
  };
}

describe("pickBestCandidate", () => {
  test("returns null for empty candidates", () => {
    assert.equal(pickBestCandidate(track(), []), null);
  });

  test("returns only candidate when one result", () => {
    const c = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    assert.equal(pickBestCandidate(track(), [c]), c);
  });

  test("prefers exact title + artist + duration match over other candidates", () => {
    const good = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    const bad = candidate("Blood - some other song", "Unknown Artist", 300);
    assert.equal(pickBestCandidate(track(), [bad, good]), good);
  });

  test("penalises live version when original has no 'live' in title", () => {
    const studio = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    const live = candidate("Knocked Loose - Blood (Live)", "Knocked Loose", 152);
    assert.equal(pickBestCandidate(track(), [live, studio]), studio);
  });

  test("does NOT penalise live version when track title contains 'live'", () => {
    const t = track({ title: "Blood (Live)" });
    const live = candidate("Knocked Loose - Blood (Live)", "Knocked Loose", 150);
    const studio = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    // Live version should not be penalised so both score similarly; just assert no crash
    const result = pickBestCandidate(t, [live, studio]);
    assert.ok(result !== null);
  });

  test("penalises remix when original has no 'remix' in title", () => {
    const studio = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    const remix = candidate("Knocked Loose - Blood (Remix)", "Knocked Loose", 150);
    assert.equal(pickBestCandidate(track(), [remix, studio]), studio);
  });

  test("penalises cover when original has no 'cover' in title", () => {
    const studio = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    const cover = candidate("Blood - Knocked Loose Cover", "SomeChannel", 145);
    assert.equal(pickBestCandidate(track(), [cover, studio]), studio);
  });

  test("penalises video that is more than 2.5x the expected duration", () => {
    const normal = candidate("Knocked Loose - Blood", "Knocked Loose", 150);
    const compilation = candidate("Best Of Knocked Loose", "SomeChannel", 5400); // 90 min
    assert.equal(pickBestCandidate(track(), [compilation, normal]), normal);
  });

  test("favours closer duration over further duration for otherwise equal candidates", () => {
    const close = candidate("Knocked Loose - Blood", "Knocked Loose", 152); // 2s off
    const far = candidate("Knocked Loose - Blood", "Knocked Loose", 175);   // 25s off
    assert.equal(pickBestCandidate(track(), [far, close]), close);
  });

  test("matches artist name from channel field", () => {
    const withChannel = candidate("Blood", "Knocked Loose", 150);
    const noArtist = candidate("Blood", "VEVOAutoGenerated", 150);
    assert.equal(pickBestCandidate(track(), [noArtist, withChannel]), withChannel);
  });

  test("partial title word match still scores above completely unrelated title", () => {
    const partial = candidate("Blood by Knocked Loose - Official Audio", "Knocked Loose", 151);
    const unrelated = candidate("Random Unrelated Video Title", "Unknown", 148);
    assert.equal(pickBestCandidate(track(), [unrelated, partial]), partial);
  });

  test("handles multi-artist track", () => {
    const t = track({ artists: ["Artist A", "Artist B"], title: "Collab" });
    const good = candidate("Artist A ft. Artist B - Collab", "VEVO", 150);
    const bad = candidate("Some Random Song", "Random Channel", 150);
    assert.equal(pickBestCandidate(t, [bad, good]), good);
  });
});
